
CREATE TABLE `BRANCH` (
`ID` INT(10) NOT NULL PRIMARY KEY AUTO_INCREMENT,
`NAME` VARCHAR(100) NOT NULL,
`DESCS` VARCHAR(200) NULL,
`OWNER` VARCHAR(100) NULL,
`HEAD` VARCHAR(100) NOT NULL,
`IMG` VARCHAR(100) NULL,
`STATE` VARCHAR(10) NULL
);

CREATE TABLE `BRANCH_MERGE` (
`ID` INT(10) NOT NULL PRIMARY KEY AUTO_INCREMENT,
`BRANCH_NAME`  VARCHAR(100) NOT NULL,
`HEAD` VARCHAR(100) NOT NULL,
`STATE` VARCHAR(10) NULL
);


